AllCops:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/EachWithObjectArgument:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Lint/EmptyEnsure:
  Enabled: true

Lint/EmptyInterpolation:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Lint/Loop:
  Enabled: true
  Safe: false

Lint/NestedMethodDefinition:
  Enabled: true
  AllowedMethods: []
  AllowedPatterns: []

Lint/RescueException:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true
  IgnoreEmptyBlocks: true
  AllowUnusedKeywordArguments: false

Lint/UnusedMethodArgument:
  Enabled: true
  AllowUnusedKeywordArguments: false
  IgnoreEmptyMethods: true
  IgnoreNotImplementedMethods: true

Lint/UselessAccessModifier:
  Enabled: true
  ContextCreatingMethods: []
  MethodCreatingMethods: []

Lint/UselessAssignment:
  Enabled: true
  SafeAutoCorrect: false

Lint/UselessElseWithoutRescue:
  Enabled: true

Lint/UselessSetterCall:
  Enabled: true
  Safe: false

Metrics/CyclomaticComplexity:
  Enabled: true
  AllowedMethods: []
  AllowedPatterns: []
  Max: 7

Performance/Count:
  Enabled: true
  SafeAutoCorrect: false

Performance/Detect:
  Enabled: true
  SafeAutoCorrect: false

Performance/ReverseEach:
  Enabled: true

Performance/Size:
  Enabled: true

Rails/Date:
  Enabled: true
  SafeAutoCorrect: false
  EnforcedStyle: flexible
  SupportedStyles: ["strict","flexible"]
  AllowToTime: true

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias
  SupportedStyles: ["prefer_alias","prefer_alias_method"]

Style/ArrayJoin:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/CaseEquality:
  Enabled: true
  AllowOnConstant: false
  AllowOnSelfClass: false

Style/ClassVars:
  Enabled: true

Style/ColonMethodCall:
  Enabled: true

Style/DoubleNegation:
  Enabled: true
  EnforcedStyle: allowed_in_returns
  SafeAutoCorrect: false
  SupportedStyles: ["allowed_in_returns","forbidden"]

Style/EachWithObject:
  Enabled: true

Style/EmptyElse:
  Enabled: true
  EnforcedStyle: both
  SupportedStyles: ["empty","nil","both"]
  AllowComments: false

Style/EvenOdd:
  Enabled: true

Style/InfiniteLoop:
  Enabled: true
  Safe: false

Style/Lambda:
  Enabled: true
  EnforcedStyle: line_count_dependent
  SupportedStyles: ["line_count_dependent","lambda","literal"]

Style/LambdaCall:
  Enabled: true
  EnforcedStyle: call
  SupportedStyles: ["call","braces"]

Style/ModuleFunction:
  Enabled: true
  EnforcedStyle: module_function
  SupportedStyles: ["module_function","extend_self","forbidden"]
  Autocorrect: false
  SafeAutoCorrect: false

Style/MultilineIfThen:
  Enabled: true

Style/MultilineTernaryOperator:
  Enabled: true

Style/NegatedIf:
  Enabled: true
  EnforcedStyle: both
  SupportedStyles: ["both","prefix","postfix"]

Style/NegatedWhile:
  Enabled: true

Style/NestedTernaryOperator:
  Enabled: true

Style/NilComparison:
  Enabled: true
  EnforcedStyle: predicate
  SupportedStyles: ["predicate","comparison"]

Style/NonNilCheck:
  Enabled: true
  IncludeSemanticChanges: false

Style/OneLineConditional:
  Enabled: true
  AlwaysCorrectToMultiline: false
