AllCops:
  Enabled: false

Lint_AmbiguousOperator:
  Enabled: true

Lint_AmbiguousRegexpLiteral:
  Enabled: true

Lint_Debugger:
  Enabled: true
  DebuggerMethods: {"Kernel"=>["binding.irb", "Kernel.binding.irb"], "Byebug"=>["byebug", "remote_byebug", "Kernel.byebug", "Kernel.remote_byebug"], "Capybara"=>["save_and_open_page", "save_and_open_screenshot"], "debug.rb"=>["binding.b", "binding.break", "Kernel.binding.b", "Kernel.binding.break"], "Pry"=>["binding.pry", "binding.remote_pry", "binding.pry_remote", "Kernel.binding.pry", "Kernel.binding.remote_pry", "Kernel.binding.pry_remote", "Pry.rescue", "pry"], "Rails"=>["debugger", "Kernel.debugger"], "RubyJard"=>["jard"], "WebConsole"=>["binding.console"]}

Lint_DuplicateMethods:
  Enabled: true

Lint_EachWithObjectArgument:
  Enabled: true

Lint_ElseLayout:
  Enabled: true

Lint_EmptyEnsure:
  Enabled: true

Lint_EmptyInterpolation:
  Enabled: true

Lint_EnsureReturn:
  Enabled: true

Lint_LiteralInInterpolation:
  Enabled: true

Lint_Loop:
  Enabled: true
  Safe: false

Lint_NestedMethodDefinition:
  Enabled: true
  AllowedMethods: []
  AllowedPatterns: []

Lint_RescueException:
  Enabled: true

Lint_ShadowingOuterLocalVariable:
  Enabled: true

Lint_UnreachableCode:
  Enabled: true

Lint_UnusedBlockArgument:
  Enabled: true
  IgnoreEmptyBlocks: true
  AllowUnusedKeywordArguments: false

Lint_UnusedMethodArgument:
  Enabled: true
  AllowUnusedKeywordArguments: false
  IgnoreEmptyMethods: true
  IgnoreNotImplementedMethods: true

Lint_UselessAccessModifier:
  Enabled: true
  ContextCreatingMethods: []
  MethodCreatingMethods: []

Lint_UselessAssignment:
  Enabled: true
  SafeAutoCorrect: false

Lint_UselessElseWithoutRescue:
  Enabled: true

Lint_UselessSetterCall:
  Enabled: true
  Safe: false

Metrics_CyclomaticComplexity:
  Enabled: true
  AllowedMethods: []
  AllowedPatterns: []
  Max: 7

Performance_Count:
  Enabled: true
  SafeAutoCorrect: false

Performance_Detect:
  Enabled: true
  SafeAutoCorrect: false

Performance_ReverseEach:
  Enabled: true

Performance_Size:
  Enabled: true

Rails_Date:
  Enabled: true
  SafeAutoCorrect: false
  EnforcedStyle: flexible
  SupportedStyles: ["strict","flexible"]
  AllowToTime: true

Style_Alias:
  Enabled: true
  EnforcedStyle: prefer_alias
  SupportedStyles: ["prefer_alias","prefer_alias_method"]

Style_ArrayJoin:
  Enabled: true

Style_AutoResourceCleanup:
  Enabled: true

Style_CaseEquality:
  Enabled: true
  AllowOnConstant: false
  AllowOnSelfClass: false

Style_ClassVars:
  Enabled: true

Style_ColonMethodCall:
  Enabled: true

Style_DoubleNegation:
  Enabled: true
  EnforcedStyle: allowed_in_returns
  SafeAutoCorrect: false
  SupportedStyles: ["allowed_in_returns","forbidden"]

Style_EachWithObject:
  Enabled: true

Style_EmptyElse:
  Enabled: true
  EnforcedStyle: both
  SupportedStyles: ["empty","nil","both"]
  AllowComments: false

Style_EvenOdd:
  Enabled: true

Style_InfiniteLoop:
  Enabled: true
  Safe: false

Style_Lambda:
  Enabled: true
  EnforcedStyle: line_count_dependent
  SupportedStyles: ["line_count_dependent","lambda","literal"]

Style_LambdaCall:
  Enabled: true
  EnforcedStyle: call
  SupportedStyles: ["call","braces"]

Style_ModuleFunction:
  Enabled: true
  EnforcedStyle: module_function
  SupportedStyles: ["module_function","extend_self","forbidden"]
  Autocorrect: false
  SafeAutoCorrect: false

Style_MultilineIfThen:
  Enabled: true

Style_MultilineTernaryOperator:
  Enabled: true

Style_NegatedIf:
  Enabled: true
  EnforcedStyle: both
  SupportedStyles: ["both","prefix","postfix"]

Style_NegatedWhile:
  Enabled: true

Style_NestedTernaryOperator:
  Enabled: true

Style_NilComparison:
  Enabled: true
  EnforcedStyle: predicate
  SupportedStyles: ["predicate","comparison"]

Style_NonNilCheck:
  Enabled: true
  IncludeSemanticChanges: false

Style_OneLineConditional:
  Enabled: true
  AlwaysCorrectToMultiline: false
